### ISSUE TITLE
[Question] Are the GPU upscale shaders automatically applied everytime?

### ISSUE THREAD

**Issue by jijirae** [hl2guide/better-mpv-config#10]
Or do I have to press F9 for every new video?

**Comment by FirstZero** [comment]
From my personal understanding and testing, the shaders are always active (aslong the video is smaller than 1080p). I dont really understand the point of the keybind either. What happens if you enable it manually with F9 is, you will have duplicate shaders running in the background massively degrading the quality.

Its probably there so you activate it manually for video above 1080p.

**Comment by hl2guide** [comment]
> From my personal understanding and testing, the shaders are always active (aslong the video is smaller than 1080p). I dont really understand the point of the keybind either. What happens if you enable it manually with F9 is, you will have duplicate shaders running in the background massively degrading the quality.
> 
> Its probably there so you activate it manually for video above 1080p.

"Its probably there so you activate it manually for video above 1080p." - yes it's an opt-in toggle intended for use in 1080p videos that are blurry enough to benefit from the sharpening.

**Comment by hl2guide** [comment]
> Or do I have to press F9 for every new video?

The GPU upscale shaders are automatically applied to videos lower than 1080p.
